name: Hello World

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Hello World
    uses: nilaycicekli/gh-actions/.github/workflows/reusable-hello.yaml@main
    with:
      environment: "dev"
      app-name: ${{ vars.APP_NAME }}
    secrets: inherit
    permissions:
      contents: read
